name: Test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Build container
        uses: docker/build-push-action@master
        with:
          context: .
          push: false
          tags: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
